apiVersion: v1
kind: Service
metadata:
  name: esports-realtime-service
spec:
  selector:
    app: esports-realtime
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
